---
- name: Restart sshguard
  become: true
  become_user: root
  ansible.builtin.service:
    name: sshguard
    state: restarted
  listen: restart sshguard

- name: Reload ufw
  become: true
  become_user: root
  community.general.ufw:
    state: reloaded
  listen: reload ufw
