---
version: '2'

services:
  portainer:
    image: portainer/portainer-ce:2.9.3
    command: -H unix:///var/run/docker.sock
    container_name: portainer
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
      - portainer-db:/data
    ports:
      - 12000:8000
      - 12443:9443



volumes:
  portainer-db:
    external: true

networks:
  host:
