---
- name: Restart ssh
  become: true
  become_user: root
  ansible.builtin.service:
    name: sshd
    state: '{{ item }}'
  when: sshd_status.rc == 0
  loop:
    - stopped
    - started
  listen: restart ssh
