---
- name: Get outdated packages
  ansible.builtin.shell:
    cmd: pip3 list -o | cut -f1 -d' ' | tr " " "\n" | awk '{if(NR>=3)print}' | cut -d' ' -f1
  register: pip_outdated
  changed_when: pip_outdated.stdout | length > 0

  tags:
    - python-update
    - update

- name: Output packages
  ansible.builtin.debug:
    msg: "Outdated packages: {{ pip_outdated.stdout_lines }}"
  tags:
    - python-update


- name: Update outdated packages # noqa package-latest
  ansible.builtin.pip:
    name: '{{ item }}'
    state: latest
  when: pip_outdated.stdout
  with_items:
    - "{{ pip_outdated.stdout_lines }}"

  tags:
    - python-update
    - update

- name: Install pip packages
  ansible.builtin.pip:
    name: '{{ pips }}'
    state: present
  tags:
    - python
    - packages
