---
- name: Install, update, and manage AUR packages
  tags:
    - aur
    - packages
  block:
    - name: Include `aur_builder` main
      ansible.builtin.include_role:
        name: aur_builder
        tasks_from: main
        apply:
          tags:
            - update
      tags:
        - update
        - install-aur-packages
        - user-packages

    - name: Update aur
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        aur_only: true
        upgrade: true
      tags:
        - update

    - name: Install aur packages
      become: true
      become_user: aur_builder
      kewlfft.aur.aur:
        name: '{{ aur }}'
        state: present
        aur_only: true
      tags:
        - install-aur-packages
        - user-packages

  always:
    - name: Include `aur_builder` cleanup
      ansible.builtin.include_role:
        name: aur_builder
        tasks_from: cleanup
        apply:
          tags:
            - update
      tags:
        - update
