---
- name: Ensure user dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0755
  loop: "{{ user_space_dirs }}"
  tags:
    - user
    - folders
    - init

- name: Ensure user log files
  ansible.builtin.copy:
    content: ""
    dest: "{{ item }}"
    force: false
    mode: "0644" # owner read/write, group read, world read
  loop: "{{ user_space_files }}"

  tags:
    - user
    - files
    - init

- name: Make zsh default shell
  become: true
  become_user: root
  ansible.builtin.user:
    name: berkeleytrue
    shell: /usr/bin/zsh
  tags:
    - init
    - user
    - zsh

- name: Make pacman colored output
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    dest: /etc/pacman.conf
    state: present
    regexp: ^(.*)Color
    line: Color
  tags:
    - system
    - init
    - user

- name: Ensure zshenv
  become: true
  become_user: root
  ansible.builtin.copy:
    src: zshenv
    dest: /etc/zsh/zshenv
    backup: true
    owner: root
    mode: "0644"
  tags:
    - init
    - resources
    - zsh
    - files
    - user

- name: Ensure fennel treesitter is present
  ansible.builtin.git:
    repo: https://github.com/sogaiu/tree-sitter-fennel.git
    dest: "{{ user_space_ts_fennel }}"
    version: master
    update: false
  tags:
    - fennel

- name: Ensure crypto-egg-go
  ansible.builtin.git:
    repo: https://github.com/berkeleytrue/crypto-egg-go.git
    dest: "{{ user_space_crypto_egg_go }}"
    version: main
    update: false
  tags:
    - crypto-egg

- name: Ensure Corpus wiki
  ansible.builtin.git:
    repo: https://github.com/BerkeleyTrue/corpus.git
    dest: "{{ ansible_env.HOME }}/docs/corpus"
    update: false
    version: master
  tags:
    - corpus

- name: Import services
  ansible.builtin.import_tasks: services.yml

- name: Ensure pulse audio auto connect
  become: true
  become_user: root
  ansible.builtin.lineinfile:
    create: true
    line: load-module module-switch-on-connect
    dest: /etc/pulse/default.pa
    mode: "0644"
  tags:
    - pulseaudio
