---
- name: Enable docker service
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Ensure Avahi is running
  become: true
  become_user: root
  ansible.builtin.systemd:
    name: avahi-daemon
    enabled: true
    state: started
