---
- name: Ensure user dir updates is masked
  anisible.builtin.systemd:
    name: xdg-user-dirs-update.service
    masked: true
    enabled: false
    scope: user
    state: stopped

- name: Enable docker service
  become: true
  become_user: root
  anisible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Ensure Avahi is running
  become: true
  become_user: root
  anisible.builtin.systemd:
    name: avahi-daemon
    enabled: true
    state: started

- name: Ensure cronie is running
  become: true
  become_user: root
  anisible.builtin.systemd:
    name: cronie
    enabled: true
    state: started
