---
- name: Running container for {{ item.name }}
  block:
  - name: Ensure Dir {{ item.name }}
    ansible.builtin.file:
      path: '{{ container_home }}/{{ item.name }}'
      mode: 0755
      state: directory

  - name: Ensure compose file {{ item.name }}
    ansible.builtin.template:
      src: '{{ item.name }}/docker-compose.yml'
      dest: '{{ container_home }}/{{ item.name }}/docker-compose.yml'
      mode: 0644

  - name: Ensure volume exists {{ item.volume }}
    community.docker.docker_volume:
      name: '{{ item.volume }}-db'

  - name: Ensure Container is up {{ item.name }}
    community.docker.docker_compose:
      project_name: '{{ item.name }}'
      project_src: '{{ container_home }}/portainer'
