---
- name: Ensure docker network
  community.docker.docker_network:
    name: web

- name: Running container block
  ansible.builtin.include_tasks: block_loop.yml
  loop:
    - name: portainer
      volume: portainer
