---
packages:
  # base
  - man-db
  - man-pages
  # x11
  - xorg-server
  - xorg-xinit # xorg startx
  - gobject-introspection # needed by taffybar
  # general
  - acpi  # client for power, batter, and thermal
  - base-devel
  - blueman
  - bluez
  - bluez-utils
  - cronie # cron impl
  - cups # printing services
  - gufw  # gui for ufw
  - gvfs # virtual file system implementation for GIO
  - keybase
  - keybase-gui
  - nss-mdns # host name resolution for cups networking
  - otf-ipafont # required to render japanese fonts
  - pkgfile # determines which package repo a file belongs to, according to /etc/pacman.conf
  - sshguard
  - ttf-dejavu # required for plymouth hexagon theme
  - ttf-fira-code # required for progress ligatures in kitty conf
  - udisks2 # disk management service
  - ufw # uncomplicated firewall
  - unclutter # hid mouse when not in use
  - xbindkeys # bind keys to commands
  - xcape  # key mapping
  - xclip # x11 clipboard cli
  - xfce4-power-manager
  - xsecurelock # secure lock screen for x11
  - xss-lock # hook into X11 screen saver extension
  # networking
  - bind # dns impl w/ dig
  - curl
  - iputils
  - traceroute
  - wget
  # desktop
  - dunst # notification daemon
  - papirus-icon-theme # needed for dunst icons
  - flameshot
  - nitrogen
  - pasystray # pulse audio systray
  - picom # compositor
  - pipewire # audio
  - pipewire-alsa # alsa compat with pipewire, uninstalls alsa
  - pipewire-pulse # pulseaudio compat with pipewire, uninstalls PulseAudio
  - plasma-desktop # for games
  - volumeicon
  - wireplumber
  # dev
  - git
  - github-cli
  - hub
  - lua-language-server
  - yaml-language-server
  - yamllint
  - wakatime
  ## haskell
  - stack
  ## terminal
  - 7zip
  - alacritty
  - aws-cli # needed for work
  - bat  # like cat but rusty
  - bat-extras # bat extras including batman man pager
  - dog  # Like dig but a good boi
  - dust  # rust based disk usage utility
  - entr  #  watch files and re-run command
  - exa  # like ls but extra
  - fd  # like find but kinder
  - figlet  # make large banners out of ascii
  - fzf
  - glow # cli markdown renderer
  - gfold # search and list git repos
  - kitty
  - lazygit
  - lsof # list open files running
  - neovim
  - playerctl # pause/play music players ci
  - procs  # rusty processes
  - ripgrep
  - shfmt
  - task  # taskwarrior
  - tealdeer  # TL;DR for deers (rusty)
  - the_silver_searcher
  - thefuck # corrects errors in previous console commands
  - timew  # timewarrior
  - tmux
  - yad # CLI to show diaglogs
  - yadm  # yet another dotfiles manager
  - zoxide  # like cd but with more warp
  - zsh
  ## automation
  - ansible
  - ansible-lint
  - docker
  - docker-compose
  - packer
  - terraform
  - vault
  ## clojure dev
  - clojure
  - leiningen
  ## node dev
  - nodejs-lts-gallium
  - npm
  ## go Dev
  - go
  - gopls # go language server
  - go-tools
  ## python
  - python-pip
  - python-setuptools
  - python2-setuptools
  ## Ethereum
  - solidity
  ## packages
  - flatpak
  # Apps
  - aspell
  - aspell-en
  - rofi
  - rofi-calc
  - gparted
  # security
  - pam-u2f
  - bitwarden-cli
