---
- name: Setup yadm
  tags:
    - yadm
  block:
    - name: Ensure Yadm
      ansible.builtin.package:
        name: yadm
        state: present

    - name: Is yadm initialized?
      ansible.builtin.command: yadm status
      ignore_errors: true
      failed_when: false
      register: yadm_status
      changed_when: false

    - name: Register yadm initialized fact
      ansible.builtin.set_fact:
        yadm_initialized: '{{ yadm_status.rc == 0 }}'

    - name: Clone Dotfiles
      ansible.builtin.command: yadm clone -f '{{ yadm_dotfiles_remote }}'
      when: not yadm_initialized
      changed_when: true
      register: yadm_cloned

    - name: Init submodules
      ansible.builtin.command: yadm submodule update --recursive --init
      when: not yadm_initialized
      changed_when: true
      register: yadm_submodules_init
