---
- name: Restart traefik
  become: true
  become_user: root
  community.docker.docker_compose:
    project_name: traefik
    project_src: '{{ traefik_folder }}'
    state: present
    restarted: true
