---
- name: Ensure docker is installed
  community.general.pacman:
    name: docker
    state: present

- name: Ensure docker group exits
  ansible.builtin.group:
    name: docker
    system: true

- name: Ensure my user is in docker group
  ansible.builtin.user:
    groups:
      - docker
    name: '{{ user }}'
    append: true
